//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraToOrder
    {
        public int ExtraOrdId { get; set; }
        public int idExtra { get; set; }
        public int idOrder { get; set; }
    
        public virtual EventExtension EventExtension { get; set; }
        public virtual Order Order { get; set; }
    }
}
