//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderArchive
    {
        public int idOrder { get; set; }
        public string tz { get; set; }
        public Nullable<int> idEvent { get; set; }
        public string orderDetails { get; set; }
        public Nullable<System.DateTime> dateOrder { get; set; }
        public Nullable<bool> statusOrder { get; set; }
    
        public virtual EventsType EventsType { get; set; }
    }
}
